name: Build


on:
  push:
    tags:
    - 'v*'


jobs:
  build:
    runs-on: ubuntu-24.04
    container: ubuntu:24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        persist-credentials: false

    - name: Version
      id: version
      run: echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

    - name: Build
      run: scripts/ci-build.sh

    - name: Rename
      run: mv prev-colors.xpi prev-colors-v${{ steps.version.outputs.version }}.xpi

    - name: Notes
      run: grep -Pzom1 "(?s)\n[##\s]*${{ steps.version.outputs.version }}.*?\n+.*?\K.*?(\n\n|$)" CHANGELOG.md | sed 's/[^[:print:]]//g' > RELEASE.md

    - name: Release
      uses: softprops/action-gh-release@v2.0.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: prev-colors-v${{ steps.version.outputs.version }}.xpi
        body_path: RELEASE.md
