name: Build


on:
  push:
    tags:
    - 'v*'


jobs:
  build:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Build
      run: scripts/ci-build.sh

    - name: Release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: prev-colors.xpi
        asset_name: prev-colors-${{ github.ref }}.xpi
        asset_content_type: application/x-xpinstall
